In [ ]:

#installations (individual)
!pip install -U pip setuptools wheel
!pip install -U 'spacy[cuda-autodetect,transformers,lookups]'
!python -m spacy download en_core_web_sm

In [ ]:
!pip install en_core_web_sm

In [10]:
import spacy

# Load Spacy model
nlp = spacy.load("en_core_web_sm")

In [5]:
import pandas as pd

# Read Dataframe
df = pd.read_csv('/content/sample_data/datensatz.csv')

# Show Dataframe
df.head()

,Text,Zusammenfassung,Kategorie
0,Ad sales boost Time Warner profit\n\nQuarterly...,TimeWarner said fourth quarter sales rose 2% t...,business
1,Dollar gains on Greenspan speech\n\nThe dollar...,The dollar has hit its highest level against t...,business
2,Yukos unit buyer faces loan claim\n\nThe owner...,Yukos' owner Menatep Group says it will ask Ro...,business
3,High fuel prices hit BA's profits\n\nBritish A...,"Rod Eddington, BA's chief executive, said the ...",business
4,Pernod takeover talk lifts Domecq\n\nShares in...,Pernod has reduced the debt it took on to fund...,business

In [7]:
# Function for Preprocessing
def preprocess_text(text):
    # Tokenization
    doc = nlp(text)
    
    # Remove stopwords, Lowercasing, Lemmatization, Remove punctuation 
    preprocessed_tokens = [token.lemma_.lower() for token in doc if not token.is_stop and not token.is_punct]
    
    # Return the preprocessed tokens as text
    preprocessed_text = " ".join(preprocessed_tokens)
    return preprocessed_text

# Preprocessing of Data 
df['Text'] = df['Text'].apply(preprocess_text)

In [8]:

df.head()

,Text,Zusammenfassung,Kategorie
0,ad sale boost time warner profit \n\n quarterl...,TimeWarner said fourth quarter sales rose 2% t...,business
1,dollar gain greenspan speech \n\n dollar hit h...,The dollar has hit its highest level against t...,business
2,yukos unit buyer face loan claim \n\n owner em...,Yukos' owner Menatep Group says it will ask Ro...,business
3,high fuel price hit ba profit \n\n british air...,"Rod Eddington, BA's chief executive, said the ...",business
4,pernod takeover talk lift domecq \n\n share uk...,Pernod has reduced the debt it took on to fund...,business

In [11]:
# balancing dataset

import pandas as pd

# Count each categorie
category_counts = df['Kategorie'].value_counts()

# Min number of the categories
min_count = min(category_counts)

balanced_dataset = pd.DataFrame()

# Iteration over each category
for category in category_counts.index:

    category_subset = df[df['Kategorie'] == category].sample(n=min_count, random_state=42)
    

    balanced_dataset = balanced_dataset.append(category_subset)



# distribution of the categories
balanced_category_counts = balanced_dataset['Kategorie'].value_counts()
print(balanced_category_counts)

sport            386
business         386
politics         386
tech             386
entertainment    386
Name: Kategorie, dtype: int64

<ipython-input-11-71979df7c168>:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  balanced_dataset = balanced_dataset.append(category_subset)
<ipython-input-11-71979df7c168>:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  balanced_dataset = balanced_dataset.append(category_subset)
<ipython-input-11-71979df7c168>:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  balanced_dataset = balanced_dataset.append(category_subset)
<ipython-input-11-71979df7c168>:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  balanced_dataset = balanced_dataset.append(category_subset)
<ipython-input-11-71979df7c168>:19: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  balanced_dataset = balanced_dataset.append(category_subset)